<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Moumen-PC" name="Test" tests="2" failures="1" timestamp="15 Sep 2016 22:00:09 GMT" time="0.064" errors="0">
  <testcase name="test_to_fail" time="0.026" classname="mymaventest.TestmavenDemo">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at mymaventest.TestmavenDemo.test_to_fail(TestmavenDemo.java:19)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test_to_fail -->
  <testcase name="test_to_pass" time="0.003" classname="mymaventest.TestmavenDemo"/>
</testsuite> <!-- Test -->
